# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DjaAsFcEzNyZx7zybqftl_rb0-EL1Aef
"""

from google.colab import drive

drive.mount('/content/drive')

# Analyze the data

import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

data=sns.load_dataset('tips')

data.head()

data.head(10)

data.tail()

data.info()

#measures of central tendancy
data.mean()

#mean
data.median()

#mode

data.mode()

#kutosis

data.kurt()

data.std()